// THE INFINITY ENGINE: Procedural Generation Core
// Capable of synthesizing 1 Billion+ unique lesson permutations

const TOPICS = [
  'Quantum Physics', 'Medieval History', 'Gastronomy', 'Diplomacy', 'Cybersecurity',
  'Space Exploration', 'Existentialism', 'Haute Couture', 'Sustainable Energy',
  'Ancient Philosophy', 'Modern Art', 'Blockchain', 'Neuroscience', 'Urban Planning'
];

const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

const ADJECTIVES = [
  'Advanced', 'Essential', 'Comprehensive', 'Mastering', 'Introduction to',
  'Expert', 'Practical', 'Contemporary', 'Classical', 'Intensive',
  'Strategic', 'Analytical', 'Creative', 'Technical', 'Professional',
  'Ultimate', 'Complete', 'Dynamic', 'Interactive', 'Applied'
];

// Deterministic pseudo-random number generator to ensure consistent results for a given ID
function seededRandom(seed: number) {
  const x = Math.sin(seed++) * 10000;
  return x - Math.floor(x);
}

export interface Course {
  id: number;
  title: string;
  level: string;
  difficulty: string;
  description: string;
  duration: string;
  modules: number;
  students: number;
  rating: string;
  xp: number;
  tags: string[];
}

export class InfinityEngine {
  static generateCourse(id: number): Course {
    const seed = id * 12345; // Simple seeding
    
    const levelIndex = Math.floor(seededRandom(seed) * LEVELS.length);
    const topicIndex = Math.floor(seededRandom(seed + 1) * TOPICS.length);
    const adjIndex = Math.floor(seededRandom(seed + 2) * ADJECTIVES.length);
    
    const level = LEVELS[levelIndex];
    const topic = TOPICS[topicIndex];
    const adjective = ADJECTIVES[adjIndex];
    
    const difficulty = level === 'C2' ? 'Expert' : level === 'C1' ? 'Advanced' : level.startsWith('B') ? 'Intermediate' : 'Beginner';
    const xp = Math.floor(seededRandom(seed + 3) * 500 + 100);
    const students = Math.floor(seededRandom(seed + 4) * 50000 + 500);
    const rating = (seededRandom(seed + 5) * 1.5 + 3.5).toFixed(1);
    const duration = Math.floor(seededRandom(seed + 6) * 40 + 5);
    const modules = Math.floor(seededRandom(seed + 7) * 20 + 5);

    return {
      id,
      title: `${adjective} ${topic}`,
      level,
      difficulty,
      description: `An autonomously generated ${level} module focusing on ${topic.toLowerCase()}. Generated by the Infinity Engine.`,
      duration: `${duration} hours`,
      modules,
      students,
      rating,
      xp,
      tags: [topic, level, difficulty, 'Procedural']
    };
  }

  static generateBatch(startIndex: number, count: number): Course[] {
    const courses: Course[] = [];
    for (let i = 0; i < count; i++) {
      courses.push(this.generateCourse(startIndex + i));
    }
    return courses;
  }
}
